import { MikroORM } from '@mikro-orm/postgresql';
import { Entity, PrimaryKey, Property, ReflectMetadataProvider } from '@mikro-orm/decorators/legacy';

@Entity()
class Ticket {
  @PrimaryKey({ generated: 'identity (start with 1000)' })
  id!: number;

  @Property()
  name!: string;
}

@Entity()
class Invoice {
  @PrimaryKey({ generated: 'by default as identity (start with 10 increment by 5)' })
  id!: number;

  @Property()
  name!: string;
}

@Entity()
class Refund {
  @PrimaryKey({ generated: 'identity (increment by -1)' })
  id!: number;

  @Property()
  name!: string;
}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    metadataProvider: ReflectMetadataProvider,
    entities: [Ticket, Invoice, Refund],
    dbName: 'identity-options',
  });
  await orm.schema.refresh();
});

afterAll(() => orm.close(true));

test('identity columns with options', async () => {
  const sql = await orm.schema.getCreateSchemaSQL();
  expect(sql).toMatch('"id" int generated always as identity (start with 1000) not null primary key');
  expect(sql).toMatch('"id" int generated by default as identity (start with 10 increment by 5) not null primary key');

  // no destructive drop/re-add of the PK on an unchanged schema
  await expect(orm.schema.getUpdateSchemaSQL()).resolves.toBe('');

  const em = orm.em.fork();
  const ticket = em.create(Ticket, { name: 't' });
  const invoices = [em.create(Invoice, { name: 'i1' }), em.create(Invoice, { name: 'i2' })];
  const refund = em.create(Refund, { name: 'r' });
  await em.flush();
  expect(ticket.id).toBe(1000);
  expect(invoices.map(i => i.id)).toEqual([10, 15]);
  expect(refund.id).toBe(-1);
});
