version: "2"

checks:
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 50
  method-count:
    config:
      threshold: 40
  return-statements:
    config:
      threshold: 7
  method-complexity:
    config:
      threshold: 7

engines:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          # make it higher so it does not report bullshit like similarity of abstract method and its implementation
          mass_threshold: 70
