import { MikroORM } from '@mikro-orm/postgresql';
import { EntityGenerator } from '@mikro-orm/entity-generator';

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: 'mikro_orm_test_eg_sequence',
    discovery: { warnWhenNoEntities: false },
    extensions: [EntityGenerator],
  });
  await orm.schema.ensureDatabase();
  await orm.schema.execute(`
    drop table if exists "ticket", "counter", "invoice", "plain" cascade;
    create table "ticket" ("id" serial primary key, "name" varchar(255) not null);
    alter sequence "ticket_id_seq" start with 1000 increment by 5 restart;
    create table "counter" ("id" serial primary key);
    alter sequence "counter_id_seq" start with 50 restart;
    create table "invoice" ("id" int generated by default as identity (start with 10 increment by 2) primary key);
    create table "plain" ("id" serial primary key);
  `);
});

afterAll(() => orm.close(true));

test('sequence options are emitted with decorators', async () => {
  const dump = (await orm.entityGenerator.generate({ entityDefinition: 'decorators' })).join('\n');
  expect(dump).toContain('@PrimaryKey({ sequence: { startWith: 1000, incrementBy: 5 } })');
  expect(dump).toContain('@PrimaryKey({ sequence: { startWith: 50 } })');
  expect(dump).toContain(
    "@PrimaryKey({ type: 'integer', generated: 'by default as identity', sequence: { startWith: 10, incrementBy: 2 } })",
  );
  expect(dump).not.toContain('start with');
  expect(dump.match(/sequence:/g)).toHaveLength(3);
});

test('sequence options are emitted with defineEntity', async () => {
  const dump = (await orm.entityGenerator.generate({ entityDefinition: 'defineEntity' })).join('\n');
  expect(dump).toContain('.sequence({ startWith: 1000, incrementBy: 5 })');
  expect(dump).toContain('.sequence(50)');
  expect(dump).toContain('.sequence({ startWith: 10, incrementBy: 2 })');
});

test('sequence options are emitted with EntitySchema', async () => {
  const dump = (await orm.entityGenerator.generate({ entityDefinition: 'entitySchema' })).join('\n');
  expect(dump).toContain('sequence: { startWith: 1000, incrementBy: 5 }');
  expect(dump).toContain('sequence: { startWith: 50 }');
});
