import { MikroORM, OracleDriver } from '@mikro-orm/oracledb';
import { EntityGenerator } from '@mikro-orm/entity-generator';

const dropTables = `begin for rec in (select table_name from user_tables where table_name in ('ticket', 'counter', 'plain')) loop execute immediate 'drop table "' || rec.table_name || '" cascade constraints'; end loop; end;`;

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    driver: OracleDriver,
    dbName: 'mikro_orm_test_eg_sequence',
    password: 'oracle123',
    schemaGenerator: { managementDbName: 'system', tableSpace: 'mikro_orm' },
    discovery: { warnWhenNoEntities: false },
    extensions: [EntityGenerator],
  });
  await orm.schema.ensureDatabase();
  await orm.schema.execute(dropTables);
  await orm.schema.execute(
    `create table "ticket" ("id" number(10, 0) generated by default as identity (start with 1000 increment by 5) not null primary key, "name" varchar2(255) not null)`,
  );
  await orm.schema.execute(
    `create table "counter" ("id" number(10, 0) generated by default as identity (start with 50) not null primary key)`,
  );
  await orm.schema.execute(
    `create table "plain" ("id" number(10, 0) generated by default as identity not null primary key)`,
  );
});

afterAll(async () => {
  // the Oracle test schema outlives the run
  await orm.schema.execute(dropTables);
  await orm.close(true);
});

test('sequence options are emitted from the identity options', async () => {
  const decorators = (await orm.entityGenerator.generate({ entityDefinition: 'decorators' })).join('\n');
  expect(decorators).toContain('sequence: { startWith: 1000, incrementBy: 5 }');
  expect(decorators).toContain('sequence: { startWith: 50 }');
  expect(decorators.match(/sequence:/g)).toHaveLength(2);

  const defineEntity = (await orm.entityGenerator.generate({ entityDefinition: 'defineEntity' })).join('\n');
  expect(defineEntity).toContain('.sequence({ startWith: 1000, incrementBy: 5 })');
  expect(defineEntity).toContain('.sequence(50)');
});
