DROP TABLE IF EXISTS `author3`;

CREATE TABLE `author3` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `created_at` VARCHAR(50) DEFAULT NULL,
  `updated_at` VARCHAR(50) DEFAULT NULL,
  `terms_accepted` tinyint(1) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `born` datetime DEFAULT NULL,
  `favourite_book_id` INTEGER DEFAULT NULL
);

DROP TABLE IF EXISTS `book3_to_book_tag3`;

CREATE TABLE `book3_to_book_tag3` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `book3_id` INTEGER DEFAULT NULL,
  `book_tag3_id` INTEGER DEFAULT NULL
);

DROP TABLE IF EXISTS `book_tag3`;

CREATE TABLE `book_tag3` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(50) DEFAULT NULL
);

DROP TABLE IF EXISTS `book3`;

CREATE TABLE `book3` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `title` VARCHAR(255) DEFAULT NULL,
  `foo` VARCHAR(255) DEFAULT NULL,
  `author_id` INTEGER DEFAULT NULL,
  `publisher_id` INTEGER DEFAULT NULL
);

DROP TABLE IF EXISTS `publisher3_to_test3`;

CREATE TABLE `publisher3_to_test3` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `publisher3_id` INTEGER DEFAULT NULL,
  `test3_id` INTEGER DEFAULT NULL
);

DROP TABLE IF EXISTS `publisher3`;

CREATE TABLE `publisher3` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(255) DEFAULT NULL,
  `type` VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS `test3`;

CREATE TABLE `test3` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(255) DEFAULT NULL
);
