DROP TABLE IF EXISTS `author2`;

CREATE TABLE `author2` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `created_at` VARCHAR(50) DEFAULT NULL,
  `updated_at` VARCHAR(50) DEFAULT NULL,
  `terms_accepted` tinyint(1) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `born` datetime DEFAULT NULL,
  `favourite_book_id` INTEGER DEFAULT NULL
);

DROP TABLE IF EXISTS `book2_to_book_tag2`;

CREATE TABLE `book2_to_book_tag2` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `book2_id` INTEGER DEFAULT NULL,
  `book_tag2_id` INTEGER DEFAULT NULL
);

DROP TABLE IF EXISTS `book_tag2`;

CREATE TABLE `book_tag2` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(50) DEFAULT NULL
);

DROP TABLE IF EXISTS `book2`;

CREATE TABLE `book2` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `title` VARCHAR(255) DEFAULT NULL,
  `foo` VARCHAR(255) DEFAULT NULL,
  `author_id` INTEGER DEFAULT NULL,
  `publisher_id` INTEGER DEFAULT NULL
);

DROP TABLE IF EXISTS `publisher2_to_test2`;

CREATE TABLE `publisher2_to_test2` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `publisher2_id` INTEGER DEFAULT NULL,
  `test2_id` INTEGER DEFAULT NULL
);

DROP TABLE IF EXISTS `publisher2`;

CREATE TABLE `publisher2` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(255) DEFAULT NULL,
  `type` VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS `test2`;

CREATE TABLE `test2` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(255) DEFAULT NULL
);
