name: 🐞 Bug report
description: Report an issue with MikroORM
labels: [ pending triage ]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a GitHub repo that can reproduce the problem you ran into. Preferably, use the [mikro-orm/reproduction](https://github.com/mikro-orm/reproduction) as a base for it. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem.
      placeholder: Reproduction
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: What driver are you using?
      multiple: false
      options:
        - "@mikro-orm/mariadb"
        - "@mikro-orm/mongodb"
        - "@mikro-orm/mysql"
        - "@mikro-orm/postgresql"
        - "@mikro-orm/sqlite"
        - "@mikro-orm/libsql"
        - "@mikro-orm/mssql"
    validations:
      required: false

  - type: input
    id: package-version
    attributes:
      label: MikroORM version
      description: Which version of the package are you using? Run `npm list <package>` in your project directory and paste the output.
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: |
        Which version of Node.js are you using? Run `node --version` in your project directory and paste the output.
        If you are using TypeScript, please include its version (`npm list typescript`) as well.
      placeholder: Node.js version 22+ is required for MikroORM
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      description: Which OS does your application run on?

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
          required: true
        - label: Read the [docs](https://mikro-orm.io/docs).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
          required: true
        - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true
