import { defineEntity, MikroORM, p } from '@mikro-orm/pglite';

const Ticket = defineEntity({
  name: 'Ticket',
  properties: {
    id: p.integer().primary().sequence({ startWith: 1000, incrementBy: 5 }),
    name: p.string(),
  },
});

const Invoice = defineEntity({
  name: 'Invoice',
  properties: {
    id: p.integer().primary().generated('by default as identity').sequence({ startWith: 10, incrementBy: 2 }),
    name: p.string(),
  },
});

test('autoincrement columns start from the declared values and clear() resets them', async () => {
  const orm = await MikroORM.init({ entities: [Ticket, Invoice], dbName: 'memory://' });
  await orm.schema.create();

  const sql = await orm.schema.getCreateSchemaSQL({ wrap: false });
  expect(sql).toContain(
    '"id" int generated by default as identity (start with 10 increment by 2) not null primary key',
  );
  expect(sql).toContain(`pg_get_serial_sequence('"ticket"', 'id')`);

  const insertRows = async () => {
    const em = orm.em.fork();
    const tickets = [em.create(Ticket, { name: 't1' }), em.create(Ticket, { name: 't2' })];
    const invoices = [em.create(Invoice, { name: 'i1' }), em.create(Invoice, { name: 'i2' })];
    await em.flush();
    return { tickets: tickets.map(t => t.id), invoices: invoices.map(i => i.id) };
  };

  const expected = { tickets: [1000, 1005], invoices: [10, 12] };
  await expect(insertRows()).resolves.toEqual(expected);
  await orm.schema.clear();
  await expect(insertRows()).resolves.toEqual(expected);
  await expect(orm.schema.getUpdateSchemaSQL({ wrap: false })).resolves.toBe('');

  await orm.close(true);
});
