import { MikroORM, Opt, OracleDriver } from '@mikro-orm/oracledb';
import { Entity, PrimaryKey, Property, ReflectMetadataProvider } from '@mikro-orm/decorators/legacy';

@Entity({ tableName: 'ticket' })
class Ticket {
  @PrimaryKey({ sequence: { startWith: 1000, incrementBy: 5 } })
  id!: number;

  @Property()
  name!: string;
}

@Entity({ tableName: 'ticket' })
class TicketChanged {
  @PrimaryKey({ sequence: { startWith: 2000, incrementBy: 10 } })
  id!: number;

  @Property()
  name!: string;
}

@Entity()
class Purchase {
  @PrimaryKey({ autoincrement: false })
  id!: number;

  @Property({ type: 'integer', autoincrement: true, sequence: { startWith: 500 } })
  number!: number & Opt;
}

async function bootstrap(entities: any[]) {
  const orm = await MikroORM.init({
    driver: OracleDriver,
    metadataProvider: ReflectMetadataProvider,
    entities,
    dbName: 'mikro_orm_test_sequence_options',
    password: 'oracle123',
    schemaGenerator: { managementDbName: 'system', tableSpace: 'mikro_orm' },
  });
  await orm.schema.refresh();
  return orm;
}

async function insertRows(orm: MikroORM) {
  const em = orm.em.fork();
  const tickets = [em.create(Ticket, { name: 't1' }), em.create(Ticket, { name: 't2' })];
  await em.flush();
  return tickets.map(t => t.id);
}

test('autoincrement columns start from the declared values and clear() resets them', async () => {
  const orm = await bootstrap([Ticket, Purchase]);

  const sql = await orm.schema.getCreateSchemaSQL({ wrap: false });
  expect(sql).toContain(
    '"id" number(10, 0) generated by default as identity (start with 1000 increment by 5) not null primary key',
  );

  await expect(insertRows(orm)).resolves.toEqual([1000, 1005]);
  await orm.schema.clear();
  await expect(insertRows(orm)).resolves.toEqual([1000, 1005]);

  await orm.close(true);
});

test('the options are applied on create only and never diffed', async () => {
  const orm = await bootstrap([Ticket, Purchase]);
  await expect(orm.schema.getUpdateSchemaSQL({ wrap: false })).resolves.toBe('');

  orm.discoverEntity(TicketChanged, Ticket);
  await expect(orm.schema.getUpdateSchemaSQL({ wrap: false })).resolves.toBe('');

  await orm.close(true);
});

test('clear() resets a non-PK autoincrement column', async () => {
  const orm = await bootstrap([Ticket, Purchase]);
  const insert = async () => {
    const em = orm.em.fork();
    const purchases = [em.create(Purchase, { id: 1 }), em.create(Purchase, { id: 2 })];
    await em.flush();
    return purchases.map(p => p.number);
  };

  await expect(insert()).resolves.toEqual([500, 501]);
  await orm.schema.clear();
  await expect(insert()).resolves.toEqual([500, 501]);

  await orm.close(true);
});
